name: aigis
description: "A Flutter project for structural pathology detection using AI."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  characters: ^1.3.0
  collection: ^1.18.0
  flutter_dotenv: ^5.0.2 # Add dotenv dependency
  ffi: ^2.0.1 # Add ffi dependency for TensorFlow Lite
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  material_color_utilities: ^0.11.0
  meta: ^1.15.0
  mime: ^1.0.6
  path: ^1.9.0
  path_provider: ^2.0.14 # Add path_provider dependency
  quiver: ^3.2.1 # Add quiver dependency
  tflite_flutter: ^0.11.0 # Ensure tflite_flutter is included
  image: ^3.0.1

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http_parser: ^4.0.2
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  lints: ^5.0.0
  matcher: ^0.12.16+1
  stack_trace: ^1.11.1
  string_scanner: ^1.2.0
  test_api: ^0.7.2
  vm_service: ^14.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - model.tflite
    - assets/images/placeholder.jpg
    - assets/images/
    - .env

        
          
        